### ISSUE TITLE
running error:ImportError: cannot import name Merge

### ISSUE THREAD

**Issue by zccoder** [wentaozhu/deep-mil-for-whole-mammogram-classification#5]
WenTao:
      hello!
      Following the step you published in the github,I found the problem below:
''
      Traceback (most recent call last):
  File "run_cnn_k_new.py", line 19, in <module>
    from convnetskeras.convnets import preprocess_image_batch, convnet
  File "/usr/local/lib/python2.7/dist-packages/convnetskeras/convnets.py", line 3, in <module>
    from convnetskeras.customlayers import crosschannelnormalization
  File "/usr/local/lib/python2.7/dist-packages/convnetskeras/customlayers.py", line 6, in <module>
    from keras.layers.core import Merge
ImportError: cannot import name Merge
''
    I have tried method to solve it,but no result.I am waiting for your answer!

**Comment by wentaozhu** [comment]
I think it is the keras version problem. You can use the proper function in the new keras version , or you can install the old version keras instead. Thanks!
